import Head from "next/head";
import Hero from "../components/Hero";
import { Layout } from "../components/Layout";
import Services from "../components/Services";
import { client } from "../lib/client";
import Menu from "../components/Menu";

export default function Home({ pizzas }) {
  return (
    // <Layout>
    <div className="py-[1rem] px-[2rem]">
      <Head>
        <title>FUDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      {/* body */}
      <Hero />
      <Services />
      <Menu pizzas={pizzas} />
    </div>
    // </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);

  return {
    props: {
      pizzas,
    },
  };
};
